### ISSUE TITLE
Not really an issue — we’re using rubicon-objc for upcoming Electron Cash for iOS

### ISSUE THREAD

**Issue by cculianu** [pybee/rubicon-objc#120]
Hi guys,

One of the other guys on our team was happy when he heard the stories of how great it was working with you guys to solve some minor issues that were present in rubicon/objc (namely the Blocks not working right as well as crucial ‘send_super’ lexical type issues), and he suggested I tell you what we’re doing with rubicon in case you wanted to know.

Anyway not sure the best way to contact you guys so I’m just posting this here.

Feel free to close it.

I just wanted to thank you for creating rubicon-objc. Not only is it very elegant as a lib, but its small footprint and great devs made it a pleasure to use and troubleshoot.

Just using it and working with dgelessus on the minor issues we found was an education. I learned a great deal both about python and about objective c internals.

Anyway not sure if you are interested or if you guys keep an”protects using our software” page or anything, but I wanted to tell you what we use rubicon-objc for (as well as Briefcase).

We ported the Electron Cash wallet (a Bitcoin Cash SPV wallet) over to iOS. Since the brunt of the core code was written in Python, we decided we needed a glue layer from Python that speaks ObjC so we could implement the UI.

Briefcase and rubicon-objc came to the rescue!

Briefcase provided an already-built setup with libpython.. and rubicon provided the bridging layer to ObjC.

Both are great tools and we’re happy to have them.

Anyway — here’s our project website: http://www.electroncash.org

We’re open source and we are planning on releasing our iOS port very soon. We’re still beta testing and haven’t officially announced it yet.

Anyway thank you and best regards!

**Comment by freakboy3742** [comment]
Thanks for the kind words - it's most appreciated.

We don't currently have a "success stories" page in our docs - but it would certainly make sense to have one. I've just added #121; once that's merged, feel free to add a line for ElectronCash.

**Comment by cculianu** [comment]
Aye, I'll do that.  We're not actually in the store yet (still beta testing but it's coming out soon!).  But as soon as we get to the store, I can link it.

Or I can link it now (I already have an app itunes id to generate a link).

Awesome!
