### ISSUE TITLE
How to terminate the terminate Async && "rubicon.objc.async" to "rubicon.objc.eventloop"

### ISSUE THREAD

**Issue by ryan-WORK** [pybee/rubicon-objc#128]
The code for the second example within the Section of Integrating asyncio with CoreFoundation is breaking:
       

       # Import the Event Loop Policy and lifecycle
       from rubicon.objc.async import EventLoopPolicy, CocoaLifecycle

       # Install the event loop policy
       asyncio.set_event_loop_policy(EventLoopPolicy())

       # Get a handle to the shared NSApplication
       from ctypes import cdll, util
       from rubicon.objc import ObjCClass

       appkit = cdll.LoadLibrary(util.find_library('AppKit'))
       NSApplication = ObjCClass('NSApplication')
       app = NSApplication.sharedApplication()

       # Get an event loop, and run it, using the NSApplication!
       loop = asyncio.get_event_loop()
       loop.run_forever(lifecycle=CocoaLifecycle(app))

So far I have refactored it to be:

        # Import the Event Loop Policy and lifecycle
        from rubicon.objc.eventloop import EventLoopPolicy, CocoaLifecycle
        import asyncio
        # Install the event loop policy
        asyncio.set_event_loop_policy(EventLoopPolicy())

        # Get a handle to the shared NSApplication
        from ctypes import cdll, util
        from rubicon.objc import ObjCClass

        appkit = cdll.LoadLibrary(util.find_library('AppKit'))
        NSApplication = ObjCClass('NSApplication')
        app = NSApplication

        # Get an event loop, and run it, using the NSApplication!
        loop = asyncio.get_event_loop()
        loop.run_forever(CocoaLifecycle(app))
        CocoaLifecycle(app).stop()

Here is the typical program output when the stop or terminate fails:
        
        Traceback (most recent call last):
        File "aio/r1a.py", line 17, in <module>
        loop.run_forever(CocoaLifecycle(app))
        File "/Users/ryancarl/.local/share/virtualenvs/RubIO-gfdP6ba6/lib/python3.7/site- 
        packages/rubicon/objc/eventloop.py", line 444, in run_forever
        self.stop()
        File "/Users/ryancarl/.local/share/virtualenvs/RubIO-gfdP6ba6/lib/python3.7/site- 
        packages/rubicon/objc/eventloop.py", line 524, in stop
        self._lifecycle.stop()
        File "/Users/ryancarl/.local/share/virtualenvs/RubIO-gfdP6ba6/lib/python3.7/site- 
        packages/rubicon/objc/eventloop.py", line 638, in stop
        self._application.terminate()
        File "/Users/ryancarl/.local/share/virtualenvs/RubIO-gfdP6ba6/lib/python3.7/site- 
        packages/rubicon/objc/api.py", line 591, in __getattr__
        type(self).__module__, type(self).__qualname__, self.objc_class.name, name)
        AttributeError: rubicon.objc.api.ObjCClass NSApplication has no attribute terminate

I have tried many attempts to stop the async action but still no luck... anyone have any thoughts or suggestions? 

Thanks in advance!

**Comment by dgelessus** [comment]
I'm not an expert on the async features of Rubicon, but I think the line `app = NSApplication` might be the problem - that sets `app` to the `NSApplication` *class*, not a `NSApplication` *instance*. You probably need to use `app = NSApplication.sharedApplication()`, like in the code from the documentation.

**Comment by ryan-WORK** [comment]
@dgelessus  I have changed the file to:
        

        # Import the Event Loop Policy and lifecycle
        from rubicon.objc.eventloop import EventLoopPolicy, CocoaLifecycle
        # importing asyncio to set event loop
        import asyncio
        # Asyncio Install the event loop policy
        asyncio.set_event_loop_policy(EventLoopPolicy())
        # Get a handle to the shared NSApplication
        from ctypes import cdll, util
        from rubicon.objc import ObjCClass
        appkit = cdll.LoadLibrary(util.find_library('AppKit'))
        NSApplication = ObjCClass('NSApplication')
        app = NSApplication.sharedApplication()
        # Get an event loop, and run it, using the NSApplication!
        loop = asyncio.get_event_loop()
        loop.run_forever(lifecycle=CocoaLifecycle(app))


Here is the error message:

        Traceback (most recent call last):
            File "aio/r1a.py", line 13, in <module>
                app = NSApplication.sharedApplication()
        TypeError: 'ObjCInstance' object is not callable



Thanks for the help!

**Comment by dgelessus** [comment]
Ah, this is a relatively common problem - it happens when you try to call a method, but it's actually a property. In this case, you need to add `NSApplication.declare_class_property('sharedApplication')` under the `NSApplication = ObjCClass('NSApplication')` line, and then remove the parentheses from the `sharedApplication` call (i. e. replace `NSApplication.sharedApplication()` with `NSApplication.sharedApplication`).

**Comment by ryan-WORK** [comment]
@dgelessus 

Super cool! It works! Thanks so much!

May I set up a PR for editing the documentation representing the correct syntax?

**Comment by dgelessus** [comment]
Merged it. Thank you for all the documentation fixes :)
