### ISSUE TITLE
Unable to run example asyncio code

### ISSUE THREAD

**Issue by infinityis** [pybee/rubicon-objc#132]
I was attempting to port over some code built on PyObjC (specifically: rumps) to instead use rubicon-objc because I wanted integrate the event loop of a native GUI app with asyncio.  After running into some difficulties, I thought I'd try to port over something even simpler (specifically: https://github.com/half0wl/simon) And when I had issues with that, I tried simply running the example code from the rubicon-objc asyncio how-to, with the addition of one line, "import asyncio":
```
# Import the Event Loop Policy and lifecycle
from rubicon.objc.eventloop import EventLoopPolicy, CocoaLifecycle

import asyncio

# Install the event loop policy
asyncio.set_event_loop_policy(EventLoopPolicy())

# Get a handle to the shared NSApplication
from ctypes import cdll, util
from rubicon.objc import ObjCClass

appkit = cdll.LoadLibrary(util.find_library('AppKit'))
NSApplication = ObjCClass('NSApplication')
NSApplication.declare_class_property('sharedApplication')
app = NSApplication.sharedApplication

# Get an event loop, and run it, using the NSApplication!
loop = asyncio.get_event_loop()
loop.run_forever(lifecycle=CocoaLifecycle(app))
```
Running this gives an error that I don't understand:
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rubicon/objc/eventloop.py", line 197, in _cf_socket_callback
    callback, args = self._writer
TypeError: cannot unpack non-iterable NoneType object
```
Any suggestions on how to get the how-to code up and running? Am I just missing something? And are there any known working examples I can refer to of open source code using rubicon-objc with asyncio?

**Comment by freakboy3742** [comment]
As always debugging asyncio code is a bit of a PITA :-)

I *can* point you at a working example using Rubicon's CocoaLifecycle - [toga](github.com/pybee/toga). The cocoa and iOS backends both use Rubicon.

You may also have some luck looking at the [unit tests for the asyncio code](https://github.com/pybee/rubicon-objc/blob/master/tests/test_async.py)

As for debugging what is going on in this case -  I tried copy/pasting that code to my own machine, and ran it (Mojave 10.14.2, Python 3.7), and it worked. It didn't *do* anything - but then, it's just starting an application, so there won't be anything visible happening. Can you share any more details about your testing environment?

**Comment by infinityis** [comment]
Thank you for the links to working examples, and thank you for confirming that it works on your machine. I'm also running Mojave 10.14.2, Python 3.7, but I realized something else; I only get the error on subsequent program runs. I can run it, then exit (via Quit on the rocket ship icon), then run it again, and immediately get the error. If I wait some amount of time, a few minutes perhaps, it will run again without error. That seems undesirable, but it may be a result of how I'm killing the application...?

**Comment by freakboy3742** [comment]
That behavior suggests the problem is a socket resource not being released. 

You say you are getting the rocket ship icon and using Quit from the application menu - I take it this means you're using a python.org installer version of Python? In that case, it's possible that what you're quitting by using the menu is *Python*, not the NSApplication - and as a result, the network resources consumed by the event loop may not be released correctly. I'm not sure if that's a problem with Python or Rubicon, though... 

For the record - I'm using a pyenv installed version, so I *don't* get the rocket ship. I'm staring the app from the command line, and terminating the program using CTRL-C. If you do the same, what behavior do you see?

**Comment by infinityis** [comment]
I'm unsure how it was installed, as Python came pre-installed (I'm using MacInCloud). I am also starting the app from the command line, but this example program will not exit via CTRL-C. Oddly enough, I am able to exit other Python programs with CTRL-C. 

As my error appears to be related to how I'm exiting Python, I'll go ahead and close this issue. Thanks again for your responses and the hint to read through the toga implementation!
