### ISSUE TITLE
Type handling - No restype encoding for...

### ISSUE THREAD

**Issue by exvito** [pybee/rubicon-objc#14]
Hello BeeWare,

Thanks for sharing rubicon-objc. I very much like the light approach at playing with Mac OS APIs with it, instead of PyObjc -- while perfectly confortable with Python, C and generic low-level systems/networking code, I confess myself as a complete Objective-C + Mac OS newbie.

(a bit of context: I've been exploring bluetooth programming on various platforms. I started with Linux, which was surprisingly nice and while waiting for some PRs to be reviewed and hopefully merged, I decided to move on to the Mac; this issue arises from my first very simple attempt).

## The facts

Exploring the Apple docs on bluetooth, in particular https://developer.apple.com/reference/iobluetooth/iobluetoothdevice?language=objc, I came up with the following script to enumerate the names and bluetooth addresses of paired devices:

```
from ctypes import cdll, util
from rubicon.objc import ObjCClass

if __name__ == '__main__':

    cdll.LoadLibrary(util.find_library('IOBluetooth'))
    IOBluetoothDevice = ObjCClass('IOBluetoothDevice')

    paired_devices = IOBluetoothDevice.pairedDevices()
    num_devices = paired_devices.count()
    for i in range(num_devices):
        device = paired_devices.objectAtIndex_(i)
        name = device.name
        address = device.getAddress()
        print('name=%r address=%r' % (name, address))
```

When run rubicon-objc complains, printing out:
```
No restype encoding for b'getAddress' (b'r^{BluetoothDeviceAddress=[6C]}')
```

With this, the names of the devices are printed out nicely, but the addresses show up as `None`.

Browsing the code, I quickly figured out the culprit in the `ObjCMethod` class. I went digging and learned a bit about Objective C type encodings (at https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html) and quickly matched the `b'r^{BluetoothDeviceAddress=[6C]}'` to the following declaration in `/System/Library/Frameworks/IOBluetooth.framework/Versions/A/Headers/Bluetooth.h`:

```
typedef struct  BluetoothDeviceAddress          BluetoothDeviceAddress;
struct  BluetoothDeviceAddress
{
        uint8_t         data[ 6 ];
};
```

(this is under 10.9.5, but per docs should be present in all the more recent OS releases)

## The way forward

Ideally, the `ObjCMethod` class, and in particular `ctype_for_encoding` would know how to handle arbitrarily complex Objective C types, including structs and arrays (I see there is some special handling for some types in the code, such as for NSPoint, NSSize and friends -- not sure why, but probably because they vary depending on the OS/CPU architecture).

A generic approach would parse an encoding like the one I got -- `b'r^{BluetoothDeviceAddress=[6C]}'` -- and dynamically create a ctypes Structure derived class such that the rubicon-objc caller would get something workable. At first sight, while not terribly complex, the parsing would need to be more sophisticated so as to handle sequences of encodings like they're specified for structures (more, regarding structures: the field name would be gone, of course, in such automatic approach).

Another, simpler, approach that worked for me was a small hack that at least returned a raw ctypes `c_void_p` when `ctype_for_encoding` fails at its task: this at least does not throw away data and allows the calling code (at the callers responsibility / knowledge) to cast that to the appropriate type and access the underlying data (or make a mistake and segfault!). :)

My hack was just replacing the `return None` right after the print for `No restype encoding for`... with a `return c_void_p`. From there, I updated my code to:

```
from ctypes import cdll, util, Structure, c_ubyte, cast, POINTER
from rubicon.objc import ObjCClass

class BluetoothDeviceAddress(Structure):
    _fields_ = [
        ('data', c_ubyte * 6),
    ]

if __name__ == '__main__':

    cdll.LoadLibrary(util.find_library('IOBluetooth'))
    IOBluetoothDevice = ObjCClass('IOBluetoothDevice')

    paired_devices = IOBluetoothDevice.pairedDevices()
    num_devices = paired_devices.count()
    for i in range(num_devices):
        device = paired_devices.objectAtIndex_(i)
        name = device.name
        address = device.getAddress()
        btda_ptr = cast(address, POINTER(BluetoothDeviceAddress))
        addr_str = ':'.join(map(lambda b: '%x' % b, btda_ptr[0].data))
        print('name=%r address=%r addr_str=%r' % (name, address, addr_str))
```

This happily did its thing and correctly printed out the address strings of the paired bluetooth devices.

## What next

Thanks for taking the time in reading this.
I'd love to hear feedback and guidance on how to move forward and I'll be happy to contribute.

PS: By the way, is there a more Pythonic approach at iterating through the elements of an NSArray? :)

**Comment by freakboy3742** [comment]
@exvito Thanks for that comprehensive writeup!

From what I can see, you've pretty much identified the source of the problem, and you're 95% of the way to what I'd call the "ideal" solution. The only modification I'd suggest is that instead of specifically casting the return value of `getAddress()` every time it is invoked, you could annotate the ctypes object for the underlying call. That way, *every* call to getAddress would be automatically processed into a useful format. This should be something like:
```
IOBluetoothDevice.getAddress.restype = POINTER(BluetoothDeviceAddress)
```

(Note - I haven't actually taken this code for a spin, but hopefully if you dig into the implementation of ObjCMethod and ObjCClass, it should be clear where I've gone awry if this doesn't work).

As for doing this dynamically - I completely agree that this would be desirable. However, I'm not sure if this is possible. The runtime type information that the Objective C runtime provides tells you that the object returned is a pointer to a structure; but doesn't tell you anything about the contents of that structure itself (since it's a raw C structure). As a result, it's not (AFAIK) possible to dynamically introspect the contents of the structure and return an appropriate value without manual intervention.

My suggestion here would be to wrap up the Bluetooth API as a standalone PyPI package that defines the `BluetoothDeviceAddress` structure (and any other interesting types in the API), and attaches it as a type annotation anywhere that it is needed. It should be a fairly simple package to define - little more than rolling out the interesting type definitions in the API as described in the .h file. If you look at Toga-cocoa, for example, this is already done for some of the more interesting GUI API calls. This also means you get to avoid the problem of accidentally redefining the `ObjCClass` (which causes a runtime error).

As for `NSArray` - that *is* an area where there is room for improvement. There is a `to_list` helper that can be used to roll out an NSArray into a Python type - but that is a one way operation.

That said, `NSArray` and `NSMutableArray` are a clearly identified and identifiable classes (as is `NSDictionary`). It should be possible to use that type identification to introduce a proxy object that provides a more Pythonic interface to those types - I just haven't got around to adding this interface. However, this is a contribution that would be most welcome, if you were so inclined to make it :-)

**Comment by exvito** [comment]
@freakboy3742 thanks for the feedback.

Your suggestion is interesting and I handn't thought of that... Unfortunatelly, trying:

```
IOBluetoothDevice = ObjCClass('IOBluetoothDevice')
IOBluetoothDevice.getAddress.restype = POINTER(BluetoothDeviceAddress)
```

...in the code sample fails because ```getAddress``` is not a class method, which seems to be what ```ObjCClass``` is prepared to handle. A similar approach as a change to my code sample works but, again, becomes repetitive -- that would be:

```
device.getAddress.method.restype = POINTER(BluetoothDeviceAddress)
```

...at each loop iteration, for each device in the array obtained from ```IOBluetoothDevice .pairedDevices ```. It does avoid the cast and better represents the meaning of the code but it is not a "set it and forget it" solution. Then again, maybe I didn't apply your suggestion to my code sample "properly". Comments very welcome. :-)

Like I said initially, I'm not familiar with Objective C and don't feel I currently have the resources to investigate/develop a "set it and forget it" solution  (although I'm glad to cooperate and contribute with guidance -- maybe it's simpler than I can fathom now).

There is, however, one **fundamental** aspect that you didn't comment on: the fact that, for this code to work, the return type handling required a change: returning ```c_void_p``` instead of ```None``` in line 722 of ```rubicon/objc/objc.py```, for the case where the ```No restype encoding for``` message is printed. Given the implementation, I don't think such a change would break existing code. What's your stance on such change? Would you accept such a PR or does it require further discussion?

Additionally, what would you say about replacing the ```print``` calls with either calls to ```logging``` or ```warnings```? I find it a bit counterintuitive to have a package like rubicon-objc doing ```prints```. :-)

Again, thanks for your feedback and thanks for the extra note on ```NSArray``` and friends. I'll keep those out of this context, to focus on the topic about type handling.

**Comment by freakboy3742** [comment]
@exvito I was afraid the "not a class property" issue would come up. I've had a quick poke around; the syntax you'll be looking for is:
```
IOBluetoothDevice.instance_methods['getAddress'].__dict__['restype']
```
However - that will only work *after* you've made the first call to `getAddress()` on an actual instance. `instance_methods` is a cache that is loaded on demand (in the `__getattr__()` call); so you need to actually make a call to populate that cache. 

A fix here would be to factor the dynamic lookup portion out of `__getattr__()`, put it into a new dictionary-like datatype, and use that data type for `instance_methods`. Going a step further, you could modify the `__getattr__()` on the ObjCClass to do the lookup, but return an *unbound* method, which is then bound to an instance when one is available.

Does that make sense? Does it give you enough detail to spelunk around a bit?

As for the change to line 722 - my apologies for the oversight on my part. The change you're proposed sounds like it would work; my only question is whether it might have some unintended consequences differentiating between genuine "return void" methods, and "return pointer to struct" methods. Does the bug *actually* exist in the call to `ctypes_for_encoding`, instead?. To my reading, the `except` case that is being triggered *shouldn't* ever be hit - as long as `method_copyReturnType()` (which is used to populate `self.return_type`) provides a meaningful value when returning a structure. Can you confirm that in your case `self.return_type` (a) is returning an ambiguous value that can't be differentiated from `void`, and (b) whether the value that is returned can be filtered in `ctypes_for_encoding`?

Changing to warnings is probably a good idea, too; most of the places I've got print statements are there as "alert the user something odd that shouldn't happen is happening" cases, so moving to warnings is probably a wise move (although it's the subject for a separate PR).

If you want to open a ticket for NSArray handling, feel free - it's definitely something that is on my longer term todo list.

**Comment by exvito** [comment]
> A fix here would be to factor the dynamic lookup portion out of __getattr__(), put it into a new dictionary-like datatype, and use that data type for instance_methods. Going a step further, you could modify the __getattr__() on the ObjCClass to do the lookup, but return an unbound method, which is then bound to an instance when one is available.
> 
> Does that make sense? Does it give you enough detail to spelunk around a bit?

Yes it does, thanks. In fact I had that somewhat figured out -- I just wondered if my lack of Objective C + existing rubicon-objc knowledge was misleading me.

I'll have a go at it and submit for discussion.


> As for the change to line 722 - my apologies for the oversight on my part. The change you're proposed sounds like it would work; my only question is whether it might have some unintended consequences differentiating between genuine "return void" methods, and "return pointer to struct" methods. Does the bug actually exist in the call to ctypes_for_encoding, instead?. To my reading, the except case that is being triggered shouldn't ever be hit - as long as method_copyReturnType() (which is used to populate self.return_type) provides a meaningful value when returning a structure. Can you confirm that in your case self.return_type (a) is returning an ambiguous value that can't be differentiated from void, and (b) whether the value that is returned can be filtered in ctypes_for_encoding?

The "return void" vs "return pointer to something" is exactly where my doubt is. After reading your comment, I agree that ```ctype_for_encoding``` should make that decision, which is perfectly possible because ```method_copyReturnType()``` returns something meaningful. Like you said, the except case is designed to not be hit.

I'll adjust the approach and submit the change for discussion.


> Changing to warnings is probably a good idea, too; most of the places I've got print statements are there as "alert the user something odd that shouldn't happen is happening" cases, so moving to warnings is probably a wise move (although it's the subject for a separate PR).

Agreed.


> If you want to open a ticket for NSArray handling, feel free - it's definitely something that is on my longer term todo list.

I'll do just that, for future reference. No commitments on PRs in the short term, though, ok? :)
