### ISSUE TITLE
Pythonic interface for NSArray / NSMutableArray

### ISSUE THREAD

**Issue by exvito** [pybee/rubicon-objc#15]
In the context of #14, a light discussion on a Pythonic interface for ```NSArray``` came up. The idea is to provide a sequence-like interface (collections.abc.Sequence?) that would simplify Python side ```NSArray``` manipulation such that, for example, instead of iterating like:

```
things = obcj.methodReturningNSArray()
for i in range(things.count()):
    thing = things.objectAtIndex_(i)
    do_something_with(thing)
```

...one could:

```
things = objc.methodReturningNSArray()
for thing in things:
    do_something_with(thing)
```

Other desirable/possible interfaces:
* Indexing as in ```things[index]```
* Length as in ```len(things)```
* Write-ability ```things[index] = something```
* Maybe a factory-like class method that would build an NSArray from a Python sequence.

Final notes:
* Implementation strategy could be either via wrapper or by customizing the Python NSArray/NSMutableArray class that rubicon-creates.
* Something similar would be desirable for NSDictionary / NSMutableDictionary.

Thanks.

**Comment by freakboy3742** [comment]
Very much +1 on this. It may not even be that difficult, either; I haven't tried it, but I *think*:
```
NSArray = ObjCClass('NSArray')
NSArray.__getitem__ = nsarray_getitem(self, index):
```
for a suitably defined `nsarray_getitem`, with similar definitions for `__len__` etc, and an overload of `__getattr__` to allow direct lookup of these dunder methods, should be all that is needed. 

Of course, it might be more complicated than that :-)

The factory method for passing in lists as `NSArray` shouldn't be needed, either; it should be possible to pass in a Python list and transparently convert it into an NSArray. However, even then, a conversion function will be required; it just won't be needed as exposed API.

**Comment by dimaqq** [comment]
A minor complication from fixed/immutable arrays and dictionaries, as their type is like `NSArray0` and `NSDictionary0`. I'm not sure how hight the trailing numbers may go...

**Comment by dgelessus** [comment]
Those names belong to the various implementation classes of `NSArray` and such. They aren't meant to be used directly (their names start with two underscores). The proper way to check if something is a `NSArray` is to use the `isKindOfClass` method.
