### ISSUE TITLE
trunk backwards incompatible

### ISSUE THREAD

**Issue by dimaqq** [pybee/rubicon-objc#30]
Following works with 0.2.3 (pypi), but does not work with trunk (github)

```
UIColor = ObjCClass("UIColor")
UIColor.blueColor()
TypeError: 'ObjCInstance' object is not callable
```

Perhaps properties don't need to be called now?

Perhaps it just deserved a release note?

**Comment by freakboy3742** [comment]
I *think* this is a change that happened somewhere around OS X 10.8 - there was a change in the Objective C API itself that changed the way properties were returned. *Nowadays*, properties don't need to be called - but that wasn't always the case.

Ideally, we'd be able to support both - but given older OS X instances are going to fade off into the sunset, I'm not sure if this is worth it...

**Comment by dimaqq** [comment]
uhm., I'm targeting iOS; granted I did make other changes in my project, perhaps that was it.

**Comment by dgelessus** [comment]
Yep, there's a special case in `ObjCInstance.__getattr__` for properties, it returns the property value directly. Sadly, properties are usually named exactly like their getters, so it's not possible to tell if that behavior is wanted, based on the attribute name. Though I think you can use `send_message(UIColor, "blueColor")`, that should work regardless of the special property syntax.

**Comment by freakboy3742** [comment]
I believe this has now been addressed; please reopen if it's still a problem for you.
