### ISSUE TITLE
Wrong automatic conversion of NSDecimalNumber to python double

### ISSUE THREAD

**Issue by mirkoluchi** [pybee/rubicon-objc#4]
The to_number function of core_foundation.py automatically converts a CFNumber to the proper python numeric type, but since CFNumberGetType() returns kCFNumberDoubleType for instances of NSDecimalNumber, the method has the side effect of converting a NSDecimalNumber to a double, which is incorrect.

I would suggest to patch the to_value and from_value methods in core_foundation.py to convert NSDecimalNumber to Decimal python object and viceversa.
I managed to patch the to_value, but my naive approach to patch the from_value method is not working, since the result of decimalNumberWithString_ is again converted to python Decimal by the to_value method itself.

Please help.

```python
def to_value(cftype):
    """Convert a CFType into an equivalent python type.
    The convertible CFTypes are taken from the known_cftypes
    dictionary, which may be added to if another library implements
    its own conversion methods."""
    if not cftype:
        return None
    if cftype.isKindOfClass_(ObjCClass('NSDecimalNumber')):
        return Decimal(ObjCClass('NSString').stringWithFormat_("%@", cftype))
    typeID = cf.CFGetTypeID(cftype)
    if typeID in known_cftypes:
        convert_function = known_cftypes[typeID]
        return convert_function(cftype)
    else:
        return cftype
def from_value(value):
    """Convert a Python type into an equivalent CFType type.
    """
    if isinstance(value, Decimal):
        # ??? HOW TO DO THIS ???
        # return ObjCInstance('NSDecimalNumber').decimalNumberWithString_(str(value))
    if isinstance(value, text):
        return at(value)
    elif isinstance(value, bytes):
        return at(value.decode('utf-8'))
    else:
        return value
```

**Comment by freakboy3742** [comment]
Thanks for the report. I think you're on the right track with your solution; there's just some non-obvious detail that is being missed. I'll take a look when I get a chance.
