### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dgelessus** [pybee/rubicon-objc#67]
We need some sort of proper documentation. At the moment we have the README, the CHANGELOG, and a few docstrings in the source code. There's also https://rubicon-objc.readthedocs.io/, which seems to be an outdated copy of the README - once we have proper docs, we should probably put them there.

I'm honestly not very familiar with documentation tools for Python. As far as I know, [Sphinx](http://www.sphinx-doc.org/) is more or less the standard system for Python documentation (it's used for the Python stdlib, Numpy and Sympy for example, and is what readthedocs uses apparently), so that would be a natural choice. One disadvantage is that (as far as I can tell) docstrings in the Python source code are completely separate from the documentation source, so the two would need to be maintained separately. (I don't think "no docstrings at all" is a good option.)

To be clear, I'm up for writing some docs myself, I just have no idea what tools one would use for the job.

**Comment by freakboy3742** [comment]
Completely agreed - and I've actually got the first cut at some docs in a repository locally that I worked on while I was on a plane. I'll push up a PR.

Yes, Sphinx is by far the easiest way to do this; but it doesn't need to be in conflict with docstrings. [This video](https://www.youtube.com/watch?v=t4vKPhjcMZg) is a good introduction to the multiple roles of documentation. Sphinx also provides (IIRC) ways to extract docstrings for the purpose of reference documentation. However, you can't autogenerate tutorials, topic guides, howtos and so on.
