### ISSUE TITLE
Bi-direction object access

### ISSUE THREAD

**Issue by Siege097** [pybee/rubicon-objc#8]
I was working through your Quickstart examples.  Is there a way to access an object in objective c that was created in python using the Rubicon bridge?  In your example you created the my_handler object, can the methods of this object be accessed from objective c?  I am trying to figure out a way to shuttle results  back from an embedded python interpreter to an objective c program.  Your examples are all on the python side.  Thanks

**Comment by freakboy3742** [comment]
Yes. When you use the `@objc_method` decorator, that registers the method as an Objective-C entry point; it can be invoked from the Python side, or from the objective C side. This is used when you start writing handlers (e.g., button press callbacks) - you write a handler with an `onPress:` selector in python, and register the instance of the (Python side) handler object to the button API. when the button is pressed, it invokes `onPress_()`on the Python side.

The only issue then is how to pass the created object back to the objective-C side. This will usually be done by setting a property, or invoking a "setHandler:" style method, but that's up to exactly what you're implementing.

**Comment by Siege097** [comment]
I am still having trouble getting objective c to see the methods I have marked with @objc_method in python.  I wanted to check if I have installed rubicon correctly.  I am using ios and could not figure out how to do a direct install, so I ran "setup install" on my host machine and installed the files to a temp directory.  I then copied the files to my app_packages directory (I am using your cookie cutter download).  I then copied the objective c test files( i.e. Example.m)  into my app. 

I can get some features to work I can run the python-side examples you provided in the ReadMe file.  I can also create objects in python using objective c class descriptions ( i.e. the Example class files in your test library).   The problem comes when I try to access anything that was created in python on the objective c side.  If you had an example of how to call an object crated in python on the  objective c side that would be very helpful.  Thanks

**Comment by freakboy3742** [comment]
@Siege097 The key point is that you can't just create the instance and have it "appear" in the objective C side. It needs to be passed in as an argument, or set as an attribute somewhere in the system. So - it's not enough to just create the instance - you have to "tell" the Objective C part which

You can see an example of this in the [Rubicon test suite](https://github.com/pybee/rubicon-objc/blob/master/tests/test_rubicon.py#L296). In that example, and `Handler` object is instantiated; it's passed to an instance of the `Example` class as the `callback` attribute. In this case, the instance of example is being created on the Python side, but could have been created objective-C side and accessed via an attribute or method. Then, when `testPeek_` and `testPoke_` are invoked, the callback (defined Python side) is invoked.

**Comment by Siege097** [comment]
Ok great, Thanks for your help
